project_name: parakeet

before:
  hooks:
    - go mod download

builds:
  - id: parakeet
    main: ./parakeet.go
    binary: parakeet
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0

dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - "creekorful/parakeet:latest"
      - "creekorful/parakeet:{{ replace .Tag \"v\" \"\" }}"
      - "creekorful/parakeet:{{ .Major }}"
    skip_push: false

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-{{ .ShortCommit }}"

release:
  prerelease: true
